default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tsarchives_development

test:
  <<: *default
  database: tsarchives_test

production:
  <<: *default
  database: tsarchives 
  username: postgres
  password: <%= ENV['PG_PASSWORD'] %>
