default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tsarchives_development

test:
  <<: *default
  database: tsarchives_test

production:
  <<: *default
  host: naskagedbinstance.crzskyasitcx.ap-northeast-1.rds.amazonaws.com 
  port: 5432 
  database: tsarchives 
  username: postgres
  password: <%= ENV['PG_PASSWORD'] %>
